# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wang Research Group | Department of Mathematics and Computer Science at Tougaloo College
tagline: >
  Machine learning.
email: xwang@tougaloo.edu
description: > # this means to ignore newlines until "baseurl:"
  Wang Research Group is based at the
  School of Natural Science in the Department of
  Mathematics and Computer Science at Tougaloo College.
  The group researches Nanopore Long-read Sequence
  and machine learning to realize entirely new devices
  and materials whose structure and composition is
  optimized from the nano- to the macro-scale, to improve
  interaction with the human body and enhance lives.
baseurl: ""
url: "https://xiuquan0418.github.io"
lang: en_GB

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

plugins:
  - jekyll-seo-tag
